name: jira-metrics2
channels: !!python/tuple
- defaults
dependencies:
- matplotlib <3.0
- numpy
- pandas <0.24
- python==3.6.8
- scipy
- seaborn
- statsmodels
- pip:
  - dateparser==0.6.0
  - jira==1.0.7
  - jira_metrics_extract
